name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "31e0673f59a74088b3c677189944dd80"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
